name = "flyn"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[vars]
VITE_FIREBASE_API_KEY = "YOUR_FIREBASE_API_KEY"
VITE_FIREBASE_AUTH_DOMAIN = "flyn-94396.firebaseapp.com"
VITE_FIREBASE_PROJECT_ID = "flyn-94396"
VITE_FIREBASE_STORAGE_BUCKET = "flyn-94396.firebasestorage.app"
VITE_FIREBASE_MESSAGING_SENDER_ID = "1490951220"
VITE_FIREBASE_APP_ID = "1:1490951220:web:38dc020a093f537fa63e61"
VITE_FIREBASE_MEASUREMENT_ID = "G-728KK3LCXM"
VITE_API_BASE_URL = "https://pjpmzvu7wn.us-east-1.awsapprunner.com/api"
VITE_API_URL = "https://pjpmzvu7wn.us-east-1.awsapprunner.com"
VITE_STRIPE_PUBLISHABLE_KEY = "YOUR_STRIPE_PUBLISHABLE_KEY"
VITE_TWITTER_CLIENT_ID = "YOUR_TWITTER_CLIENT_ID"
VITE_SLACK_CLIENT_ID = "YOUR_SLACK_CLIENT_ID"
VITE_TIKTOK_CLIENT_KEY = "YOUR_TIKTOK_CLIENT_KEY"
VITE_LINKEDIN_CLIENT_ID = "YOUR_LINKEDIN_CLIENT_ID"
VITE_FACEBOOK_APP_ID = "YOUR_FACEBOOK_APP_ID"
VITE_CHATBOT_TENANT_ID = "flyn-master"
