/**
 * Core workflow types for FLYN Automation Orchestrator
 * These types represent the compiled workflow JSON from FSD2's Workflow Compiler
 */

// ============================================================================
// WORKFLOW DEFINITION TYPES (Input from FSD2 Compiler)
// ============================================================================

/**
 * A compiled workflow ready for execution
 * This is the contract between FSD2 (Workflow Compiler) and FSD1 (Orchestrator)
 */
export interface CompiledWorkflow {
    id: string;
    name: string;
    version: number;
    tenantId: string;
    compiled_nodes: CompiledNode[];
    compiled_edges: CompiledEdge[];
    execution_plan: ExecutionPlan;
    metadata: WorkflowMetadata;
    /** Whether this workflow is published and should respond to real trigger events */
    isActive?: boolean;
}

/**
 * A node in the compiled workflow graph
 */
export interface CompiledNode {
    id: string;
    type: NodeType;
    name: string;
    config: Record<string, unknown>;
    position?: { x: number; y: number }; // For visual reference
}

/**
 * Node types supported by the orchestrator
 */
export enum NodeType {
    // Core execution nodes
    TRIGGER = 'trigger',
    ACTION = 'action',
    CONDITION = 'condition',

    // Wait/Resume nodes
    WAIT = 'wait',
    APPROVAL = 'approval',

    // Routing nodes
    AI_ROUTER = 'ai_router',
    SPLIT = 'split',  // Parallel execution
    JOIN = 'join',    // Wait for parallel paths
    DECISION = 'decision',  // True/False branch routing

    // Control nodes
    LOOP = 'loop',
    ITERATOR = 'iterator',  // frontend palette name for the loop node
    END = 'end',

    // Data nodes
    MONGODB = 'mongodb',
    POSTGRESQL = 'postgresql',
    MYSQL = 'mysql',
    MERGE = 'merge',

    // Plugin nodes
    CRM = 'crm',
    VAPI = 'vapi',
    WEBRTC = 'webrtc',
    HR = 'hr',
    CHURCH = 'church',
    AI_ACTION = 'ai_action',  // AI text generation node
    FREELANCER = 'freelancer',
    COACHES = 'coaches',

    // Dynamic agent nodes
    VOICE_AGENT = 'voice_agent',

    // Inbox / Messaging nodes
    INBOX_TRIGGER = 'inbox_trigger',
    SEND_REPLY = 'send_reply',
    SEND_WHATSAPP = 'send_whatsapp',

    // AI-authored / AI-patched code node (see Exchanged_docs/AI_Custom_Nodes_Design.md)
    CUSTOM = 'custom',
}

/**
 * An edge connecting two nodes
 */
export interface CompiledEdge {
    id: string;
    source: string;      // Source node ID
    target: string;      // Target node ID
    sourceHandle?: string; // For nodes with multiple outputs
    condition?: EdgeCondition;
}

/**
 * Condition for edge traversal
 */
export interface EdgeCondition {
    type: 'expression' | 'ai_confidence' | 'approval_result' | 'default';
    expression?: string;        // For expression type: e.g., "data.amount > 1000"
    threshold?: number;         // For AI confidence: e.g., 0.8
    comparisonOperator?: '>=' | '<=' | '>' | '<' | '==' | '!=';
    value?: unknown;
}

/**
 * Execution plan generated by the compiler
 */
export interface ExecutionPlan {
    startNodeId: string;
    endNodeIds: string[];
    nodeOrder: string[];        // Topological order for reference
    parallelPaths: ParallelPath[];
}

export interface ParallelPath {
    splitNodeId: string;
    joinNodeId: string;
    branches: string[][];       // Array of node ID sequences per branch
}

/**
 * Workflow metadata
 */
export interface WorkflowMetadata {
    createdAt: Date;
    updatedAt: Date;
    createdBy: string;
    publishedAt?: Date;
    tags?: string[];
    description?: string;
}

// Trigger types that the dispatch service matches against
export type WorkflowTriggerEventType = 'inbox_trigger' | 'trigger' | 'webhook' | 'schedule';

// ============================================================================
// WORKFLOW INSTANCE TYPES (Runtime state)
// ============================================================================

/**
 * Status of a workflow run
 */
export enum WorkflowRunStatus {
    PENDING = 'pending',
    RUNNING = 'running',
    WAITING = 'waiting',      // Paused, waiting for external event
    COMPLETED = 'completed',
    FAILED = 'failed',
    CANCELLED = 'cancelled',
}

/**
 * A running instance of a workflow
 */
export interface WorkflowRun {
    id: string;
    workflowId: string;
    workflowVersion: number;
    tenantId: string;
    status: WorkflowRunStatus;

    // Trigger information
    triggeredBy: TriggerSource;
    triggerData: Record<string, unknown>;

    // Execution state
    currentNodeIds: string[];   // Active execution tokens
    context: ExecutionContext;  // Shared context across nodes

    // Timestamps
    startedAt: Date;
    completedAt?: Date;
    lastActivityAt: Date;

    // Error tracking
    error?: WorkflowError;
}

export interface TriggerSource {
    type: 'webhook' | 'schedule' | 'manual' | 'event' | 'campaign';
    sourceId?: string;
    metadata?: Record<string, unknown>;
}

export interface ExecutionContext {
    variables: Record<string, unknown>;   // Workflow-level variables
    nodeOutputs: Record<string, unknown>; // Outputs indexed by nodeId
    resumeData?: Record<string, unknown>; // Data from resume events
}

export interface WorkflowError {
    nodeId: string;
    message: string;
    code: string;
    stack?: string;
    timestamp: Date;
}
